name: "Set plugin name"
description: "Set a PLUGIN_NAME environment variable with from a configuration variable or from the repository name"
inputs:
  plugin-name:
    description: "Plugin name to use"
    required: false
runs:
  using: composite
  steps:
    - name: Get the plugin name
      id: set-plugin-name
      shell: bash
      run: |
        if [ -n "${{ inputs.plugin-name }}" ]; then
          PLUGIN_NAME="${{ inputs.plugin-name }}"
        else
          PLUGIN_NAME="${GITHUB_REPOSITORY#*/}"
        fi
        PLUGIN_NAME="${PLUGIN_NAME,,}"
        echo "PLUGIN_NAME=${PLUGIN_NAME}" >> $GITHUB_ENV
